version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tono-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tono123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - tono_pg_data:/var/lib/postgresql/data

volumes:
  tono_pg_data:
